#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# non interactive fast directory switch
alias jj='fasd_cd'
alias bge='e ~/.Brewfile'
alias bgi='brew bundle --global'

export FZF_CTRL_T_OPTS="--preview 'bat --style=numbers --color=always {} | head -100' --height=50% --reverse"
alias ff="fzf --preview 'bat --style=numbers --color=always {} | head -100' --height=50% --reverse"


export LESS="-R"
export LESSGLOBALTAGS="global"


# Match variants
local -a word_functions
word_functions=(backward-kill-word backward-word
                capitalize-word down-case-word
                forward-word kill-word
                transpose-words up-case-word)
for f in $word_functions; do
  autoload -Uz $f-match
  zle -N $f $f-match
done

# Word boundaries are normal + $WORDCHARS with subword mode on
autoload -U select-word-style
select-word-style Normal

# get our vim on
bindkey -v

# We still want a bunch of emacs binding here
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^f' forward-char
bindkey '^b' backward-char
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line

# Some vimlike shortcuts for history nav
bindkey '^k' up-history
bindkey '^j' down-history

# CTRL-r for backwards history of course
# bindkey '^r' history-substring-search-up
# bindkey '^s' history-substring-search-down

# Pressing f and d at the same time escapes to normal mode
bindkey 'fd' vi-cmd-mode

autoload -Uz surround
zle -N delete-surround surround
zle -N add-surround surround
zle -N change-surround surround
bindkey -a 'cs' change-surround
bindkey -a 'ds' delete-surround
bindkey -a 'ys' add-surround
bindkey -a 's' add-surround
bindkey -a 'S' add-surround
bindkey -M visual S add-surround

# bindkey -a 'b' backward-word
# bindkey -a 'w' forward-word
bindkey -a 'v' visual-mode
bindkey -a 'V' edit-command-line
bindkey -a '^V' edit-command-line
bindkey -a 'y' vi-yank
bindkey -a 'Y' vi-yank-eol

# wordstyle=standard-subword
# zstyle ':zle:*' word-chars "$WORDCHARS"
# zstyle ':zle:*' skip-whitespace-first false
# zstyle ':zle:*' word-style $wordstyle

# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Jenv setup
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# Android studio setup
export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"

# The fuck
eval $(thefuck --alias)
